workflows:
  ios-workflow:
    name: Weather Master iOS Build
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install iOS platform support
        script: |
          flutter create . --platforms=ios
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build iOS app for sideloading
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
